// Generated by CoffeeScript 1.7.1
exports.index = function(req, res) {
  return res.render("index");
};

exports.upload = function(req, res) {
  var form, multiparty, util;
  util = require("util");
  multiparty = require('multiparty');
  form = new multiparty.Form({
    autoFiles: true,
    uploadDir: "./tempUploads"
  });
  return form.parse(req, function(err, fields, files) {
    if (err) {
      res.writeHead(500, {
        "content-type": "text/plain"
      });
      res.send("ERROR: uploading\n\n");
    }
    console.log("upload handled", fields, files);
    return res.json(util.inspect({
      message: "upload complete",
      fields: fields,
      files: files
    }));
  });
};
