// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["msgbus", "backbone", "apps/intro/show/views", "controller/_base"], function(msgBus, Backbone, Views, AppController) {
    var Controller, _ref;
    return Controller = (function(_super) {
      __extends(Controller, _super);

      function Controller() {
        _ref = Controller.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Controller.prototype.initialize = function() {
        var _this = this;
        this.layout = this.getLayoutView();
        this.listenTo(this.layout, "show", function() {
          _this.titleRegion();
          _this.caroRegion();
          return _this.steamRegion();
        });
        return this.show(this.layout);
      };

      Controller.prototype.titleRegion = function() {
        var view;
        view = this.getTitleView();
        return this.layout.titleRegion.show(view);
      };

      Controller.prototype.steamRegion = function() {
        var view;
        view = this.getSteamView();
        return this.layout.steamRegion.show(view);
      };

      Controller.prototype.caroRegion = function() {
        var view;
        view = this.getCaroView();
        return this.layout.caroRegion.show(view);
      };

      Controller.prototype.getTitleView = function() {
        return new Views.Title;
      };

      Controller.prototype.getSteamView = function() {
        return new Views.Steambtn;
      };

      Controller.prototype.getCaroView = function() {
        return new Views.Caro;
      };

      Controller.prototype.getLayoutView = function() {
        return new Views.Layout;
      };

      return Controller;

    })(AppController);
  });

}).call(this);
