// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['msgbus', 'marionette', 'apps/intro/show/templates'], function(msgBus, Marionette, Templates) {
    var _Layout, _options, _ref, _ref1, _ref2, _ref3, _title;
    return {
      Title: _title = (function(_super) {
        __extends(_title, _super);

        function _title() {
          _ref = _title.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        _title.prototype.template = _.template(Templates.title);

        return _title;

      })(Marionette.ItemView),
      Caro: _title = (function(_super) {
        __extends(_title, _super);

        function _title() {
          _ref1 = _title.__super__.constructor.apply(this, arguments);
          return _ref1;
        }

        _title.prototype.template = _.template(Templates.caro);

        return _title;

      })(Marionette.ItemView),
      Steambtn: _options = (function(_super) {
        __extends(_options, _super);

        function _options() {
          _ref2 = _options.__super__.constructor.apply(this, arguments);
          return _ref2;
        }

        _options.prototype.template = _.template(Templates.steambtn);

        _options.prototype.triggers = {
          "click button": "button:clicked"
        };

        return _options;

      })(Marionette.ItemView),
      Layout: _Layout = (function(_super) {
        __extends(_Layout, _super);

        function _Layout() {
          _ref3 = _Layout.__super__.constructor.apply(this, arguments);
          return _ref3;
        }

        _Layout.prototype.template = _.template(Templates.layout);

        _Layout.prototype.className = "container";

        _Layout.prototype.regions = {
          titleRegion: "#title-region",
          caroRegion: "#caro-region",
          steamRegion: "#steam-region"
        };

        return _Layout;

      })(Marionette.Layout)
    };
  });

}).call(this);
