// Generated by CoffeeScript 1.6.3
/*
Module dependencies.
*/


(function() {
  var app, config, express, http, path, routes, util;

  express = require("express");

  routes = require("./routes");

  http = require("http");

  path = require("path");

  util = require("util");

  app = express();

  app.set("port", process.env.PORT || 3000);

  app.set('views', './views');

  app.set("view engine", "jade");

  app.use(express.logger("dev"));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(express.cookieParser("your secret here"));

  app.use(express.session());

  app.use(app.router);

  app.use(express["static"]('./public'));

  config = require('./config.json')[app.get('env')];

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", routes.index);

  app.post("/upload", routes.upload);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port=" + (app.get('port')) + " environment=" + (app.get('env')) + " apikey=" + config.APIKEY);
  });

}).call(this);
