// Generated by CoffeeScript 1.6.3
(function() {
  define(["globalize", "config/jquery/jquery", "config/underscore/templatesettings", "config/marionette/templatecache", "config/marionette/application"], function() {});

}).call(this);
