// Generated by CoffeeScript 1.6.3
(function() {
  define(function(require) {
    return {
      itemview: require("text!apps/header/list/templates/itemview.htm"),
      view: require("text!apps/header/list/templates/headerview.htm")
    };
  });

}).call(this);
